[package]
name = "time-oracle-kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tezos-smart-rollup = "0.1"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"